ATPassport/ATPassport/urls.py
from django.contrib import admin
from django.urls import include,  path
from django.views.generic import RedirectView

urlpatterns = [
    path('webportal/', include('webportal.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

#Redirect Base Url to webPortal app
urlpatterns += [
    path('', RedirectView.as_view(url='/webportal/', permanent=True)),
]

ATPassport/webportal/urls.py
from django.urls import path
from .views import EquipmentListView

from . import views
# Use static() to add URL mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', views.index, name='index'),
    path('providerloans', views.providerloans, name='providerloans'),
    path('userloans', views.userloans, name='userloans'),
    path('equipment', views.EquipmentListView, name='equipment'),
    path('equipmentdelete/<int:id>',views.delete_Equipment, name='equipmentdelete'),
    path('loanEquipment/<int:id>',views.loanEquipment, name='loanEquipment'),
    path('returnEquipment/<int:id>',views.returnEquipment, name='returnEquipment')

]

#Remove for production enviornment
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ATPassport/webportal/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from datetime import date


class User(AbstractUser):
    pass

# Create your models here.
class AtUser(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key= True)

    firstName = models.CharField(max_length=50)
    lastName = models.CharField(max_length=50)
    dob = models.DateField('Date Of Birth')
    email = models.EmailField

    def __str__(self):
        return self.firstName + " " + self.lastName 

#Single Provider user account will be linked to each Loan. 
class Provider(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, primary_key= True)
    name = models.CharField(max_length=100)

    #Could potentially make this contain a list of staff users as well as part of group permissions. 

    def __str__(self):
        return self.name

class AtCategory(models.Model):
    name = models.CharField(max_length=100)
    desc = models.CharField(max_length=500)

    def __str__(self):
        return self.name
    @classmethod
    def create(cls):
        category = cls(name='generic', desc='generic')
        category.save()
        return category



class Equipment(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=500)
    atcategory = models.ForeignKey(AtCategory, on_delete=models.CASCADE)
    inventory = models.IntegerField(default= 10)
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)
    imgsrc = models.CharField(max_length=10000, default="https://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Empty_set_symbol.svg/640px-Empty_set_symbol.svg.png")

    def __str__(self):
        return self.name
    
    @classmethod
    def create(cls, name, description, atcategory, inventory, provider,imgsrc):
        equipment = cls(name=name, 
                        description=description,
                        atcategory=atcategory, 
                        inventory=inventory, 
                        provider=provider,
                        imgsrc=imgsrc)
        return equipment

   
    
class LoanInstance(models.Model):
    due_date = models.DateField()
    equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE)
    atuser = models.ForeignKey(AtUser, on_delete=models.CASCADE)
    provider = models.ForeignKey(Provider, on_delete=models.CASCADE)

    @property
    def is_overdue(self):
        """Check whether the Loan is overdue based on due date and current date."""
        return bool(self.due_date and date.today() > self.due_date)
    
    @classmethod
    def create(cls, due_date, equipment, atuser, provider):
        loaninstance = cls(due_date=due_date, equipment=equipment, atuser=atuser, provider=provider)
        return loaninstance
    
    class Meta:
        permissions = (("can_return", "Can set loan as returned"),)

ATPassport/webportal/forms.py
from django import forms 
from .models import AtCategory, Equipment


class CreateEquipmentForm(forms.Form):
    name = forms.CharField(max_length=100)
    description = forms.CharField(widget=forms.Textarea(attrs={"rows":5}),max_length=500)
    atcategories = AtCategory.objects.all()
    imgsrc = forms.CharField(max_length=10000)
    
    CATEGORIES = ()
    for item in atcategories:
        print(item.name, item.desc)
        CATEGORIES = CATEGORIES + ((item.name, item.name),)
 
    atcategory = forms.CharField(label='Equipment Category:', widget=forms.Select(choices=CATEGORIES))
    inventory = forms.IntegerField(min_value=0)

    class Meta:
        model = Equipment

ATPassport/webportal/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic.list import ListView
from .models import AtUser, LoanInstance, Provider, Equipment, AtCategory
from .forms import CreateEquipmentForm
from django.http import HttpResponseRedirect
from datetime import datetime
from dateutil.relativedelta import relativedelta

app_name = 'webportal'

@login_required
def index(request):
    context={}
    return render(request, 'webportal/index.html', context) 

@login_required
def userloans(request):
    atuserid = request.user.id
    atuser = AtUser.objects.get(user_id=atuserid)
    
    userloans = LoanInstance.objects.filter(atuser=atuserid)

    num_userloans = userloans.count()

    context={
        'atuser': atuser,
        'userloans': userloans,
        'num_userloans': num_userloans,
    }
    return render(request, 'webportal/userloans.html', context)

@login_required
def providerloans(request):
    provideruser = request.user
    provider = Provider.objects.get(pk=provideruser)
    providerloans = LoanInstance.objects.filter(provider=provider)
        
    context ={
        'provider': provideruser,
        'providerloans': providerloans,
    }
    return render(request, 'webportal/providerloans.html', context)


@login_required
def EquipmentListView(request): 

    def DeleteEquipment(request, obj_id):
        object = get_object_or_404(Equipment, pk=obj_id)
        object.delete()

    if request.method == 'POST':
        createform = CreateEquipmentForm(request.POST)
        if createform.is_valid():
            print(createform.cleaned_data) 
            # data = form.cleaned_data['name']
            # print(data);
            cd = createform.cleaned_data
            provideruser = request.user
            provider = Provider.objects.get(pk=provideruser)
            catString = createform.cleaned_data['atcategory']
            
            eq = Equipment.create(createform.cleaned_data['name'],
                                  createform.cleaned_data['description'],
                                  AtCategory.objects.get(name=catString),
                                  createform.cleaned_data['inventory'],
                                  provider,
                                  createform.cleaned_data['imgsrc'])
            eq.save()
            return HttpResponseRedirect("/webportal/equipment")
    elif request.method == 'PUT':
        print("putputput")

    else:
        createform = CreateEquipmentForm
    context={
        'createform': createform,
          'equipment': Equipment.objects.all,
          'deletefunc': DeleteEquipment
    }
    return render(request, 'webportal/equipment_list.html', context)


@login_required
def delete_Equipment(request, id):
    print("IN DELETE")
    equipment = get_object_or_404(Equipment, pk=id)
    equipment.delete()
    return HttpResponseRedirect("/webportal/equipment")


@login_required
@permission_required('webportal.add_loaninstance', raise_exception=True)
def loanEquipment(request, id):
    print("Im loaning some equipment")
    equipment = get_object_or_404(Equipment, pk=id)
    if equipment.inventory > 0: 
        equipment.inventory = equipment.inventory - 1
        threemonthstime = datetime.today() + relativedelta(months=3)
        
        atuserid = request.user
        print(atuserid)
        atuser = AtUser.objects.get(pk=atuserid)
        loaninstance = LoanInstance.create(due_date=threemonthstime, equipment=equipment, atuser=atuser, provider=equipment.provider)
        
        loaninstance.save()
        equipment.save()
        return HttpResponseRedirect("/webportal/userloans")

    else:
        raise Exception("Inventory not sufficent to loan this equipment")
    
@login_required
@permission_required('webportal.delete_equipment', raise_exception=True)
def returnEquipment(request, id):
    print("Im returning a loan")
    loan = get_object_or_404(LoanInstance, pk=id)
    loan.delete()
    return HttpResponseRedirect("/webportal/providerloans")

    
   
    

ATPassport/templates/webportal/base_template.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    {% block title %}<title>ATPass</title>{% endblock %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'ATPassport/style.css' %}">
    <link rel="stylesheet" href="{% static 'ATPassport/normalize.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
  </head>
  <body class="body-wrapper">
    <nav>
      <ul class="sidebar-nav">
      {% if user.is_authenticated %}
        <li class="navitem">
          <span class='usernameLabel'>User:</span>
          <span class='username'>{{ user.get_username }}</span>
        </li>
        <li class="navitem">
          <a href="{% url 'equipment' %}"><button aria-label="View Equipment" class="nice-button">View Equipment Library</button></a>
        </li>
        {% if perms.webportal.add_loaninstance %}
        <li class="navitem">
          <a href="{% url 'userloans' %}"><button class="nice-button">View My Loans</button></a>
        </li>
        {% endif %}
        {% if perms.webportal.delete_equipment %}
        <li class="navitem">
          <a href="{% url 'providerloans' %}"><button class="nice-button">View All Loans</button></a>
        </li>
        {% endif %}
        <li class="navitem">          
          <a href="http://127.0.0.1/#/home/"><button class="nice-button">Your Documents</button></a>
        </li>
        <li class="navitem"><a href="{% url 'logout' %}?next={{ request.path }}"><button class="nice-button">Logout</button></a></li>
      {% else %}
        {% comment %} <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li> {% endcomment %}
      {% endif %}
      </ul>
    </nav>
    
    <main>
      {% block content %}
      {% endblock %}
    </main>
  </body>
</html>

ATPassport/templates/webportal/catalog.html
{% extends "./base_template.html" %}
  
{% block content %}
  <h1>Equipment Catalog</h1>
    <h2>Categories</h2>
    <ul>
        {% for category in atcategories %}
        <li> {{category.name}}</li>
        {% end for %}
    </ul>
    <h2>All Equipment</h2>
    <ul>
      {% for item in equipment %}
      <li>{{item.name}}</li>
      {% end for%}
    </ul>

{% endblock %}

ATPassport/templates/webportal/equipment_list.html
{% extends "./base_template.html" %}

{% block content %}
<div class="col-container">
  <div>
    <div class="banner" >
      <h1>Equipment</h1>
    </div>
    <div class="col-container justcenter">
      {% for equipment in equipment %}
        <div class="equipment-card">
          <div class="item-box">
            <div class="item-column">
              <img class="loan-image"  src="{{ equipment.imgsrc }}" alt="{{ equipment.name }}">
            </div>
            <div class="item-column">
              <table class="styled-table">
                <tr>
                  <td>Equipment Name:{{ equipment.name }}</td>
                </tr>
                <tr>
                  <td>Desc:{{ equipment.description }}</td>
                </tr>
                <tr>
                  <td>Amount :{{ equipment.inventory }}</td>
                </tr>
              </table>
              {% if perms.webportal.add_loaninstance %}  
                {% if equipment.inventory > 0 %}
                  <a href="{% url 'loanEquipment' equipment.id %}"><button class="nice-button">Loan Out</button></a>
                {% else %}
                  <button class="nice-button" disabled=true>No Items Available</button>
                {% endif %}  
              {% endif %}
              {% if perms.webportal.delete_equipment %}
                <a href="{% url 'equipmentdelete' equipment.id %}"><button class="nice-button">Delete</button></a>
              {% endif %}
            </div>
          </div>
        </div> 
      {% empty %}
        <li>No Equipment Available</li>
      {% endfor %}
    {% if perms.webportal.add_equipment %}
      <h2>Add new Equipment</h2>
      <div class="form-layout col-container justcenter">
        <form action="" method="POST">
        {% csrf_token %}
          <table>
            {{ createform.as_table }}
          </table>
          <div class="row-container justcenter">
            <input class="nice-button" type="submit" value="Submit">
          </div>
        </form>
      </div>
    {% endif %}
  </div>
{% endblock %}

ATPassport/templates/webportal/index.html
{% extends "./base_template.html" %}
  
{% block content %}

<div class="row-container justcenter">
  <div class="col-container justcenter">
    <h1>AT-Pass</h1>
    <h2>The Assistive Technology Passport</h2>
    <p>
        Welcome to the Assistive Technology Passport Webportal. The links above will alllow you to view and interact with our equipment library and document store. 
    </p>
  </div>
</div>
{% endblock %}

ATPassport/templates/webportal/providerloans.html
{% extends "./base_template.html" %}
  
{% block content %}
<div class="banner" >
  <h1>{{ provider }} Loans</h1>  
</div>
{% for loan in providerloans %}
  <div class="row-container justcenter">
      <div class="equipment-card  ">
        <div class="item-box">
          <div class="item-column">
            <img class="loan-image" width="100" height="140"  src="{{ loan.equipment.imgsrc }}" alt="{{loan.equipment.name}}">
          </div> 
        <div class="item-column ">
          <table class="styled-table">
            <tr>
              <td>Equipment: {{loan.equipment.name}} </td>
            </tr>
            <tr>
              <td>Description: {{loan.equipment.description}}</td>
            </tr>
            <tr>
              <td>Category: {{loan.equipment.atcategory}}</td>
            </tr>
            <tr>
              <td>User: {{loan.atuser}}</td>
            </tr>
            <tr>
              <td>Due Date: {{loan.due_date}}</td>
            </tr>
            <tr>
              <td>Overdue: {{loan.is_overdue}}</td>
            </tr>
           </table>
            {% if perms.webportal.delete_equipment %}
            <div class="row-container justcenter">
              <a href="{% url 'returnEquipment' loan.id %}"><button class="nice-button">Return Loan</button></a>
            </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endfor %}
  
{% endblock %}

ATPassport/templates/webportal/userloans.html
{% extends "./base_template.html" %}

{% block content %}
<div class="row-container justcenter">
  <div class="col-container justcenter">
  <h1>Your Loans</h1>
  <p>
    Welcome {{ atuser }}!
    You have {{ num_userloans }} loans. 
  </p>
  {% for loan in userloans %}
  <div class="equipment-card">
    <div class="item-box">
      <div class="item-column">
        <img class="loan-image" width="100" height="140"  src="{{ loan.equipment.imgsrc }}" alt="{{ loan.equipment.name }}">
      </div>
      <div class="item-column">
        <table class="styled-table">
          <tr>
            <td>Loan Item:{{loan.id}}</td>
          </tr>
          <tr>
            <td>Equipment: {{loan.equipment.name}} </td>
          </tr>
          <tr>
            <td>Description: {{loan.equipment.description}}</td>
          </tr>
          <tr>
            <td>Category: {{loan.equipment.atcategory}}</td>
          </tr>
          <tr>
            <td>Provider: {{loan.provider.name}}</td>
          </tr>
          <tr>
            <td>Due Date: {{loan.due_date}}</td>
          </tr>
          </table>
        </div>
      </div>
    </div>    
  {% endfor %}
  </div>
</div>   
{% endblock %}